version: "2"
services:
    ui:
        image: webapp-ui
        restart: always
        stdin_open: true
        ports:
            - "3000:3000"
        volumes:
            - ./ui:/ui
            - /ui/node_modules
        links:
            - server
        networks:
            - webappnetwork
    server:
        image: webapp-server
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./server:/server
            - /server/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        environment:
            MONGO_INITDB_DATABASE: props
        volumes:
            - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
            - 27017:27017
        command: 
            mongod
        networks:
            - webappnetwork
    mongo_seed:
        container_name: mongo_seed
        build: ./mongo
        networks:
        - webappnetwork
        depends_on:
        - mongodb
networks:
    webappnetwork:
        driver: bridge
